### ISSUE TITLE
Seemingly long time to reload

### ISSUE THREAD

**Issue by stockholmux** [jprichardson/reload#11]
Hi-
I'm using `supervisor`, `reload` and chrome but it's taking about 6-7 seconds for the reload to actually occur. Is this normal? I've tried modifying the `p` value on `supervisor ` but it doesn't seem to matter.

What happens-
- File is changed
- Almost immediately the browser changes to 'This webpage is not available'
- 6-7 seconds elapse
- Page is reloaded

I'm on OS X with Node 10.30.

**Comment by alallier** [comment]
Try using the new reload delay option true, that may fix your problem https://github.com/jprichardson/reload#reloadhttpserver-expressapp-delay

**Comment by trevorhreed** [comment]
Had the same symptoms as OP; @alallier's issue resolved this for me.
