### ISSUE TITLE
Specify Custom URL instead of Localhost

### ISSUE THREAD

**Issue by IbnSaeed** [jprichardson/reload#14]
Hello

Is it possible to specifiy custom URL to load the browser page.

I am running docker and the reload is working fine but it opens the site in localhost:port

i have a custom IP forwarded to my host machine, is it possible to use a custom ip instead of localhost ?

Also, the reload takes 1 to 2 seconds to reload the page in the browser.

**Comment by alallier** [comment]
I assume you are using, the browser development option. I would be willing to put up a PR to accommodate your request if JP would like that feature added to reload?

**Comment by jprichardson** [comment]
Sure, I think that'd be useful.

**Comment by alallier** [comment]
This was taken care of by pull request #28
