### ISSUE TITLE
Allow the user to specify their start page when using the browser development option

### ISSUE THREAD

**Issue by alallier** [jprichardson/reload#19]
As an enhancement

**Comment by alallier** [comment]
As an enhancement

**Comment by jprichardson** [comment]
Yeah, I like that idea. PR welcomed :)

**Comment by alallier** [comment]
Okay great, it will come soon, working on another enhancement currently.

**Comment by jprichardson** [comment]
https://github.com/jprichardson/reload/releases/tag/0.3.0
