### ISSUE TITLE
Websockets Issues

### ISSUE THREAD

**Issue by martindsouza** [jprichardson/reload#30]
Really like reload and has been especially useful when developing presentations using [reveal.js](https://github.com/hakimel/reveal.js)!

It works for me by doing a full page refresh each time I make a change to a folder it's listening to. The catch is that they're a lot of errors in the console. Here are some screen shots to help debug (in order as they appear)

![image](https://cloud.githubusercontent.com/assets/2925726/10989405/2e7810d4-8404-11e5-93d8-a73eed41bfbe.png)

![image](https://cloud.githubusercontent.com/assets/2925726/10989412/3aa0665e-8404-11e5-8b42-e0314e5f2b39.png)

![image](https://cloud.githubusercontent.com/assets/2925726/10989416/45bd7b8a-8404-11e5-9d11-42a32d1a9a21.png)

_There's a lot more like the last image_

If there's anything you'd like me to test please let me know.

Thanks.

**Comment by alallier** [comment]
When you are getting the errors is that when you server is down or restarting?

**Comment by alallier** [comment]
I was also able to replicate this issue while working on issue #35. Will look into this further

**Comment by alallier** [comment]
Closing for now please try the new version (1.0.0), as it re-writes the WebSockets. Please re-open if you still are having issues.
