### ISSUE TITLE
Cannot get index.html when adding url parameter

### ISSUE THREAD

**Issue by SuTran** [jprichardson/reload#37]
Everything work well if I just open index.html only.
But when I adding some parameter to the url (ex. index.html?query=abc). I got below message
```
 errno: -4058,
 code: 'ENOENT',

```
Please help me to solve this issue. 
For more information, I use **_reload -b_** mode

**Comment by alallier** [comment]
Can you provide more information? Maybe some screen shots of your terminal?

**Comment by SuTran** [comment]
Hi @alallier,

Thank you for your reply.
I created this repo: https://github.com/SuTran/load-demo
After execute **_reload -b_** command. The browser opened up with the **index.html** correctly. But when I access **index.html?query=abc**, the error happen

**Comment by alallier** [comment]
I can't seem to replicate your problem.

![image](https://cloud.githubusercontent.com/assets/13004518/13691999/81f8568c-e70b-11e5-816f-12540ab07fa5.png)
 
I believe what you are experiencing isn't related to reload. Can you provide anything else. Is the code you uploaded in the repo the exact code you are running?

**Comment by alallier** [comment]
So I took a look at your example app in your repo and I think you were going about using reload in the wrong way. You shouldn't be using the command line style, you should be using the in [app style](https://github.com/jprichardson/reload#using-reload-with-express-4) . So you would add the script tag to your html `<script src="/reload/reload.js"></script>` and then use a program like supervisor to run your `server.js` file. Then you are running your own custom server file and as you make a change supervisor restarts the server, reload sees this and reloads the page for you automatically.

**Comment by alallier** [comment]
Closing for now, please try the new version (1.0.0). If you are still having issues with this please re-open issue.
