### ISSUE TITLE
error: cannot get /browser-sync/browser-sync-client.2.9.12.js

### ISSUE THREAD

**Issue by jmls** [jprichardson/reload#39]
trying to use reload, and when I fire it up I get this error : what does it mean ? I do have a folder 

```
./node_modules/browser-sync-client
```

but I suspect that the web server is not pointing to something somehwere. The site does load (with my files) but I get this error in the server logs

**Comment by alallier** [comment]
Closing for now, please try the new version (1.0.0). If you are still having issues with this please re-open issue.
