### ISSUE TITLE
For some reason this is not working as it should

### ISSUE THREAD

**Issue by shadowofsoul** [jprichardson/reload#47]
Hi,

first time using it.

i have a express app, that i'm trying to hot reload the code by a textfile flag. i'm doing:

      var reload = require('require-reload')(require);
      var reloadhttp = require('reload');

      server = http.createServer(app);

      reloadServer = reloadhttp(server, app);

      server.listen(app.get('port'), function(){
      console.log("Express server listening on port " + app.get('port'));
      });

      try {
        processLogs       = reload('./routes/processLogs.js');
      } catch (e) {
          //if this threw an error, the api variable is still set to the old, working version
          console.error("Failed to reload api.js! Error: ", e);
      }

      reloadServer.reload();

so, here i'm reloading the code with `require-reload` and the http server with `reload` (`reloadServer.reload();`). i'm sure the code is reloaded (with `require-reload`), why after a tests, the `console.log()` output is updated. but on the web end, the code is not updated (it should be after the `reloadServer.reload()`)

maybe i'm doing something wrong, so let me know how i can diagnose and fix this.

**Comment by alallier** [comment]
Are you restarting you server every time(/are you using something like supervisor, nodemon, etc.)?

**Comment by shadowofsoul** [comment]
no, nothing. at testing only the ssh with the server running. in the future i will use PM2 to maintain it running in case it crashes. the idea was to actually use the combination of this 2 to reload the changes in the code whiteout reloading the server itself (i don't want to reload the whole server on production, i could interrupt an user operation with the server)

**Comment by alallier** [comment]
If you're not restarting the server this line `reloadServer.reload();` only gets called once

**Comment by alallier** [comment]
I see you closed this issue, did you end up figuring out what the problem was?

**Comment by shadowofsoul** [comment]
no, but if i need to reload the server to push more changed on it, it doesn't work for me on production. i prefer to schedule times to update the files or test of nodemon + forever maybe works :)
