### ISSUE TITLE
hardcoded /*html route - how to reload with jade views folder?

### ISSUE THREAD

**Issue by sascha1337** [jprichardson/reload#50]
( i am using express middleware )

**Comment by alallier** [comment]
When are referring to a hardcoded route are you referring to [here](https://github.com/jprichardson/reload/blob/master/lib/reload-server.js#L40) or [here](https://github.com/jprichardson/reload/blob/master/lib/reload-server.js#L47)?

If so it seems you are trying to use reload in it's command line form. Instead you should be [https://github.com/jprichardson/reload#using-reload-in-express](Using reload in Express), this doesn't tie you to anything hardcoded.

I would also recommend looking at the [sample app](https://github.com/jprichardson/reload/tree/master/expressSampleApp) and then see how you can modify it to work with your jade views.

If I misunderstood you, please provide more information and I'd be happy to help!

**Comment by alallier** [comment]
Closing, no feedback in awhile. Happy to re-open at a later time if needed!
