### ISSUE TITLE
require reload throws in prod

### ISSUE THREAD

**Issue by cadilhac** [jprichardson/reload#52]
I realize this is not reload specific, but I'm sure you will be able to help as I'm starting with node.
If I install reload as devdependency, I will get an exception when calling require('reload') in prod. What is the best practice to load your script only in dev env.
Thanks

**Comment by alallier** [comment]
Sorry for the long reply on this. I would use `process.env`. Pass what mode you are running in on the command line or parse it as an argument in your `app.js`. Then use `if` statements to make checks based on what environment you are in. I'd recommended checking out [Process environments](https://nodejs.org/api/process.html#process_process_env) and googling some examples of this.

I'm going to close this an open issue, and we can continue to discuss this in private or in the closed issue.

Let me know if you need more help!

**Comment by cadilhac** [comment]
Thanks. Used dotenv package for that.
