### ISSUE TITLE
Conflict with socket.io

### ISSUE THREAD

**Issue by tashburn** [jprichardson/reload#58]
I have an app that uses both reload and socket.io, and the browser console shows an error:

> WebSocket connection to 'ws://localhost:3000/sock/?EIO=3&transport=websocket&sid=7MUoA1CIsrDduaamAAAA' failed: Invalid frame header

When I don't use reload, the error doesn't appear.
﻿
Despite the error, socket.io still works for me, strangely. I want to eliminate the annoying error message though.

I'm assuming reload uses socket.io too. I thought that there might be a path conflict, so I tried using a different path for socket.io (/sock instead of /socket.io), but it didn't help.
​

**Comment by alallier** [comment]
Reload uses [ws](https://www.npmjs.com/package/ws). It's a possible port conflict issue I imagine. Reload needs to support cutsom config for port as right now it uses the appplication's port. So opening your own WebSocket can cause a conflict. A temporary fix would be to move your WebSocket to another port. I will open an issue on reload supporting custom ports for WebSockets now.

**Comment by tashburn** [comment]
Thanks

**Comment by alallier** [comment]
Okay with closing this?

**Comment by tashburn** [comment]
Sure

**Comment by alallier** [comment]
Okay great thanks for the issue, feel free to track the status of this over at #57.
