### ISSUE TITLE
Pause from client side

### ISSUE THREAD

**Issue by xoorath** [jprichardson/reload#60]
Hey,

I'd like to put in a feature request for the client side: I'd like the ability to ignore reload requests.

Use case:

> I'm making a video game and a lot of times I want to hot-reload the game when I'm working on the server or client files. However other times I want to be able to freely code without stopping the running game. If we could pause the reloading (effectively: ignore requests) I could add a tickbox to the game page that would allow it to temporarily ignore these reloads.

Thanks for the great tool,
Xoorath

**Comment by alallier** [comment]
This could be achieved with your own vanilla JavaScript

**Comment by xoorath** [comment]
How do I prevent the client `reload.js` from reloading? Is there some API I'm unaware of?

**Comment by alallier** [comment]
You could add a checkbox that when clicked removes the reload script tag from the DOM. It's a little hacky but it should work for your use case.

**Comment by xoorath** [comment]
I see. I'd still like to leave this open as a feature request, since it should be pretty trivial, not too bloaty, and helpful for some folks.

I'll try getting something to work. Alternatively I may just package my own `client-reload.js` with my app that has this feature. I'm not sure, but I'll give some workaround a go.

Thanks for the input.

**Comment by alallier** [comment]
The typical use case for reload, is it is active in development mode and not active in production mode.

Typically this is done by having a conditional in the script section of your HTML so something like this (assuming you are using a templating engine):

```html
<if env='development'>
  <script type='text/javascript' src='/js/development.js'></script>
  <script src='/reload/reload.js'></script>
</if>
<else>
  <script type='text/javascript' src='/js/production-min.js'></script>
</else>
```

Then you just run your app in two different modes depending on what you need. I'm not shutting down this idea. I'm open to others opinions on this ( @jprichardson )

**Comment by xoorath** [comment]
Cool, yeah - that's exactly what I do but with dust.js.

```
    {#release} {:else}
    <script src="/reload/reload.js"></script>
    {/release}
```

The use case for me is : I'm developing the game and for example I'm near the end state of "level 5". I want to keep this open as I have further work/profiling/whatever to do, but I want to keep coding. 

Being able to pause this reloading can be pretty helpful for me. I can see myself and the rest of my team using this very regularly.

**Comment by alallier** [comment]
@xoorath thank you for opening up this issue, the team ( @jprichardson and I agree) that this type of control should be on a project by project basis, keeping reload as light and simple as possible.
