### ISSUE TITLE
require is not defined?

### ISSUE THREAD

**Issue by miliu99** [jprichardson/reload#65]
When I try to include reload.js in my index.html, I got this error in browser log:

Uncaught ReferenceError: require is not defined
    at reload.js:1

this is my index.html:

```
<!DOCTYPE html>
<html>

<head lang="en">
    <base href="/">
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css"/>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css"/>
    <link href="styles.css" rel="stylesheet" />

    <!-- Polyfill(s) for older browsers -->
    <script src="node_modules/core-js/client/shim.min.js"></script>
    
    <script src="node_modules/zone.js/dist/zone.js"></script>
    <script src="node_modules/systemjs/dist/system.src.js"></script>
    <script src="node_modules/reload/lib/reload.js"></script>

    <!-- Configure SystemJS -->
    <script src="systemjs.config.js"></script>
    <script>
      System.import('main.js').catch(function(err){ console.error(err); });
    </script>
</head>

<body>
    <pm-app>Loading App...</pm-app>
</body>

</html>
```

What do I miss?

**Comment by peterwillis** [comment]
change this line:

> <script src="node_modules/reload/lib/reload.js"></script>

to this:
> <script src="node_modules/reload/lib/reload-client.js"></script>

**Comment by alallier** [comment]
No there is more to it than that, you should be including this script tag `<script src="/reload/reload.js"></script>` and you have to initialize reload in express. Please refer to the [sample app](https://github.com/jprichardson/reload/tree/master/expressSampleApp) as an example.

**Comment by yamboy1** [comment]
Its trying to run require() which is a nodejs function in a web browser. Take out that script and see what happens. And make sure that you are using v1.1.3.

**Comment by alallier** [comment]
Closing due to no response. I can re-open with new information and/or response
