### ISSUE TITLE
Don't need reload.js

### ISSUE THREAD

**Issue by yamboy1** [jprichardson/reload#76]
In the sample express application. I found that it runs fine when I deleted the `<script src="/reload/reload.js"></script>` line. When do you need to include that tag?

**Comment by alallier** [comment]
That's impossible it needs that script tag, so when the browser requests it, the express route created by reload will send the reload-client file.

**Comment by yamboy1** [comment]
I'll have another look at it

**Comment by yamboy1** [comment]
I cloned a fresh copy and it still worked. Heres what I did (in ubuntu terminal). Node version v6.10.2. Npm version v4.5.0.
```bash
$ git clone https://github.com/jprichardson/reload.git
$ cd reload
$ npm install # in reload directory
$ cd expressSampleApp
$ npm install # in reload/expressSampleApp directory
```

Then I removed the script tag, saved the file, and run:
```bash
$ ./node_modules/reload/bin/reload server.js -d ./public
```

**Comment by yamboy1** [comment]
Just had a look at the inspector in my browser. Turns out that reload-server.js is inserting the reload.js file into the webpage. I've made a pull request #79.

**Comment by alallier** [comment]
Please see [comment](https://github.com/jprichardson/reload/pull/79#issuecomment-298170429) left in #79. Going to close.
