### ISSUE TITLE
Difference between express reload and static reload

### ISSUE THREAD

**Issue by yamboy1** [jprichardson/reload#88]
What are the differences between the express reload and the static reload, apart from the fact that the express reload uses express

EDIT: Differences about the end result, not how it works

**Comment by alallier** [comment]
Not sure what your question is

**Comment by AckerApple** [comment]
If I understand the loosely worded question like I think I do : The difference in end result is none, they are one in the same. Express has static as a dependency, essentially express runs on static. The reload package, during command line execution only, actually uses express's version of static as seen here : [reload-static-invoke](https://github.com/jprichardson/reload/blob/master/lib/reload-server.js#L49)

Perhaps that is what is being asked? I also do not exactly know what is meant by "express reload" and "static reload". In my fork of [ack-reload](https://npmjs.org/package/ack-reload), I removed the dependency of express by only depending on express's static package dependency.
