### ISSUE TITLE
How do I run the Express sample app

### ISSUE THREAD

**Issue by yamboy1** [jprichardson/reload#89]
I tried running `node server.js`, but that just said `Web server listening on port 3000` and wouldn't reload.

**Comment by AckerApple** [comment]
Just trying to be helpful. I believe you are suppose to navigate to http://localhost:3000

I could be wrong.

In my fork, I added an API option of open:true, which then auto opens a browser as well as navigates the browser window to http://local host:3000 . See https://www.npmjs.com/package/ack-reload#arguments

I hope my comment it welcomed

**Comment by yamboy1** [comment]
I can access the webpage, but the reload part isn't working

**Comment by yamboy1** [comment]
Let my clarify what I want to know.

When I run the server, it runs at localhost:3000 and I can access it. However it doesn't 'Automatically refresh and reload your code in your browser when your code changes' (quoted from README). How do i get it to reload the page

**Comment by yamboy1** [comment]
I'll put in a pull request for open: true. That seem's very useful.

**Comment by alallier** [comment]
It's up to you to use some type of file watcher to restart the server, like [supervisor](https://www.npmjs.com/package/supervisor), [nodemon](https://www.npmjs.com/package/nodemon), etc.

**Comment by alallier** [comment]
@yamboy1 by the way reload already has a flag to auto open the browser [`-b`](https://github.com/jprichardson/reload#usage-for-command-line-application)

**Comment by yamboy1** [comment]
Could you give me an example.

**Comment by yamboy1** [comment]
Does that flag work with the sample app aswell

**Comment by alallier** [comment]
Example on what? And that flag will work whenever you use reload as a command line tool

**Comment by yamboy1** [comment]
Do i just run `supervisor node server.js`

**Comment by yamboy1** [comment]
I finally got it working by running `supervisor -w public server.js` and adding `javascript var watch = require('watch')` and `watch.watchTree(path.join(__dirname, '/public'), function (f, curr, prev) {
  // Fire server-side reload event
  reloadServer.reload()
})` (copied from readme) to my server.js.

You should probably add that into the sample app and explain how to run it in the readme file

**Comment by alallier** [comment]
You don't need this `watch.watchTree(path.join(__dirname, '/public'), function (f, curr, prev) { // Fire server-side reload event reloadServer.reload() })` for the sample app. Just have supervisor restart the server and reload will reload the page for you. It is that simple.

**Comment by yamboy1** [comment]
Is this the right command: `supervisor -w public server.js`

**Comment by yamboy1** [comment]
If I comment out that watch code, it doesn't reload. Using that code is the only way to make it work

**Comment by AckerApple** [comment]
Using the reload package, as an API outside bin command line invocation, I felt was lacking in functionality like auto opening a browser and watching files. When I forked into ack-reload, I added "open", "watch", "html5Mode" and other arguments into the API. [ack-reload](https://www.npmjs.com/package/ack-reload#arguments)

**Comment by alallier** [comment]
@yamboy1 is this issue still a problem?

**Comment by yamboy1** [comment]
No

**Comment by alallier** [comment]
Okay good, I opened #100 as it might be helpful to some
