### ISSUE TITLE
seems work but doesn't reload the browser

### ISSUE THREAD

**Issue by cocodrino** [jprichardson/reload#9]
Hi, I'm trying it with an express app, I follow the steps, when I change a file I can see in the terminal :

       Express server listening on port 3000
       DEBUG: crashing child
      DEBUG: Starting child process with 'node app.js'
      Express server listening on port 3000

this change every time than I change my file and save it...but my browser is not reloaded...I'm using linux and the latest firefox

thanks!..

**Comment by dotku** [comment]
@cocodrino you need include the file in front end view files as well.

**Comment by alallier** [comment]
Closing for now, please check out the new version (1.0.0) and see if this still is an issue. If it is please re-open the issue. Also, I recommend checking out the [express sample app](https://github.com/jprichardson/reload/tree/master/expressSampleApp) to get a better idea of how reload works.
