### ISSUE TITLE
Add appveyor CI

### ISSUE THREAD

**Issue by yamboy1** [jprichardson/reload#91]
You should probably use Appveyor as well as Travis because Travis only tests on Linux, while appveyor tests on Windows. There might be a build which passes Travis, but fails to work on your Windows computer.

**Comment by alallier** [comment]
I'm open to this, this sounds like a good idea. Would you like to open a PR demonstrating it? *Target master please*

**Comment by alallier** [comment]
Useful Link: https://www.appveyor.com/

**Comment by yamboy1** [comment]
I've made a Pull Request #92.

**Comment by alallier** [comment]
Closed by #92. Again thank you again for this recommendation it was a great idea!
